name: Echo Hello on PR Merge to Staging

on:
    pull_request:
        types: [closed]
        branches:
            - staging

jobs:
    deploy-staging:
        runs-on: ubuntu-latest
        environment: Staging
        steps:
            - name: Echo Hello
              run: echo "Deploying to Staging"

    deploy-production:
        runs-on: ubuntu-latest
        environment: Production
        steps:
            - name: Echo Hello
              run: echo "Deploying to Production"